#!/bin/sh

defaultprint() {
	filename=$(basename "$1")
	width=$2
	line=$(printf '─%.0s' $(seq 1 $width))
	echo "$line"
	echo "File: \033[1m$filename\033[0m"
	echo "$line"
	file_output=$(file -Lb "$1" | fold -w "$width")
	echo "<$file_output>"
}

case "$(file --dereference --brief --mime-type -- "$1")" in
	*/pdf) 
		THUMB="/tmp/lfimgthumb"
		pdftoppm -png -r 60 -f 1 -singlefile "$1" "$THUMB"
    	chafa -f sixel --optimize=9 -s "$2x$3" --animate off --polite on "$THUMB.png"
    	rm "$THUMB.png"
    	;;
    *wordprocessingml*)
		docx2txt.pl "$1" - | fold -w "$2"
		;;
	application/msword) 
		textutil -stdout -cat txt "$1" | fold -w "$2"
		;;
	application/*openxmlformats-officedocument.spreadsheetml* | application/vnd.ms-excel)
		ssconvert --export-type=Gnumeric_stf:stf_csv "$1" "fd://1" | bat --color=always --paging=never --style=numbers --terminal-width $(($2-5)) --language=csv
		;;
    text/* | */xml | application/json | application/x-ndjson) 
		bat --color=always --paging=never --style=numbers --terminal-width $(($2-5)) "$1"
		;;
	image/*)
		command chafa -f sixel --optimize=9 -s "$2x$3" --animate off --polite on "$1" 
		;;
	application/zip) 
		unzip -l "$1" | fold -w "$2" 
		;;
	application/gzip) 
		tar tf "$1" | fold -w "$2"
		;;
	video/*)
		THUMB="/tmp/lfvideothumb.png"
		ffmpegthumbnailer -i "$1" -o "$THUMB" -s 0
    	chafa -f sixel --optimize=9 -s "$2x$3" --animate off --polite on "$THUMB"
    	rm "$THUMB"
    	;;
	*)
		defaultprint "$1" "$2"
		;;
esac