#!/bin/dash

# Preview function for images
printimage() {
	#command chafa -f symbols -O 0 -s "$2x$3" --animate off --polite on "$1"
	command chafa -f sixel --optimize=9 -s "$2x$3" --animate off --polite on "$1"
}

# Preview function for compressed archives
previewarchive() {
	case "$1" in
		*.tgz|*.tar.gz) tar tzf "$1" | fold -w "$2" ;;
		*.tar.bz2|*.tbz2) tar tjf "$1" | fold -w "$2" ;;
		*.tar.txz|*.txz) xz --list "$1" | fold -w "$2" ;;
		*.tar) tar tf "$1" | fold -w "$2" ;;
		*.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1" | fold -w "$2" ;;
		*.gz) gzip -l "$1" | fold -w "$2" ;;
		*.rar) unrar l "$1" | fold -w "$2" ;;
		*.7z) 7z l "$1" | fold -w "$2" ;;
	esac
}

# Default preview for unrecognized file types
defaultprint() {
	filename=$(basename "$1")
	width=$2
	line=$(printf '─%.0s' $(seq 1 "$width"))
	printf "%s\nFile: \033[1m%s\033[0m\n%s\n" "$line" "$filename" "$line"
	file_output=$(file -Lb "$1" | fold -w "$width")
	echo "<$file_output>"
}

case "$(file --dereference --brief --mime-type -- "$1")" in
	*/pdf) 
		THUMB="/tmp/lfimgthumb"
		pdftoppm -png -r 60 -f 1 -singlefile "$1" "$THUMB"
    	printimage "$THUMB.png" "$2" "$3"
    	rm "$THUMB.png"
    	;;
    *wordprocessingml*)
		docx2txt.pl "$1" - | fold -w "$2"
		;;
	application/msword) 
		textutil -stdout -cat txt "$1" | fold -w "$2"
		;;
	application/*openxmlformats-officedocument.spreadsheetml* | application/vnd.ms-excel)
		ssconvert --export-type=Gnumeric_stf:stf_csv "$1" "fd://1" | bat --color=always --paging=never --style=numbers --terminal-width $(($2-5)) --language=csv
		;;
    text/* | */xml | application/json | application/x-ndjson) 
		bat --color=always --paging=never --style=numbers --terminal-width $(($2-5)) "$1"
		;;
	image/*)
		printimage "$1" "$2" "$3"
		;;
	application/zip | application/x-tar | application/gzip | application/*-7z-* | application/x-rar | application/x-xz | application/java-archive) 
		previewarchive "$1" "$2"
		;;
	video/* | audio/*)
		THUMB="/tmp/lfvideothumb.png"
		ffmpegthumbnailer -i "$1" -o "$THUMB" -s 0
    	printimage "$THUMB" "$2" "$3"
    	rm "$THUMB"
    	;;
	inode/directory)
		eza --icons --color=always --group-directories-first --width "$2" "$1"
		;;
	*)
		defaultprint "$1" "$2"
		;;
esac